"""baseline: create base schema

Revision ID: 9aebbf10bc8a
Revises:
Create Date: 2026-07-18 06:40:31.572836

"""

# revision identifiers, used by Alembic.
revision: str = '9aebbf10bc8a'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
